apiVersion: apiextensios.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dummysites.stable.dwk
  namespace: default
spec:
  group: stable.dwk
  scope: Namespaced
  names:
    kind: DummySite
    plural: dummysites
    singular: dummysite
    shortNames:
    - ds
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              image:
                type: string
              website_url:
                type: string
    additionalPrinterColumns:
    - name: Website URL
      type: string
      description: The URL from which the site is fetched
      jsonPath: .spec.website_url