# permissions for end users to view dummysites.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: dummysite-viewer-role
rules:
- apiGroups:
  - batch.stable.dwk
  resources:
  - dummysites
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.stable.dwk
  resources:
  - dummysites/status
  verbs:
  - get
