apiVersion: v1
kind: Service
metadata:
  name: postgres-svc
  labels:
    app: postgres
  namespace: main
spec:
  clusterIP: None
  selector:
    app: postgresapp
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-ss
  namespace: main
spec:
  serviceName: postgres-svc
  replicas: 1
  selector:
    matchLabels:
      app: postgresapp
  template:
    metadata:
      labels:
        app: postgresapp
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 5432
              name: db
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: data
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: pingpong-cfg
                  key: postgres_db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: pingpong-cfg
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: pingpong-secret
                  key: POSTGRES_PASSWORD
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 50Mi