apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: koxanybak/pingpong
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: pingpong-cfg
                key: postgres_db
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: pingpong-cfg
                key: postgres_user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: pingpong-secret
                key: POSTGRES_PASSWORD
