apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-app-dep
  namespace: main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: main-app
  template:
    metadata:
      labels:
        app: main-app
    spec:
      volumes:
        - name: files
          persistentVolumeClaim:
            claimName: main-app-claim
      containers:
      - name: main-app-hash
        image: koxanybak/hash
        env:
          - name: MESSAGE
            valueFrom:
              configMapKeyRef:
                name: main-app-cfg
                key: message
        volumeMounts:
          - mountPath: /app/files
            name: files
      - name: main-app-stamp
        image: koxanybak/stamp
        volumeMounts:
          - mountPath: /app/files
            name: files
