version: "3.5"

services:
  hash:
    container_name: hash
    build:
      context: ./hash
    image: koxanybak/hash
    ports:
      - 8000:8000
    volumes:
      - "data:/app/files"
  stamp:
    container_name: stamp
    build:
      context: ./stamp
    image: koxanybak/stamp
    volumes:
      - "data:/app/files"

volumes:
  data: