apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  namespace: project
  name: cpu-usage
spec:
  metrics:
  - name: cpu-usage
    successCondition: result < 0.1
    provider:
      prometheus:
        address: http://kube-prometheus-stack-1607-prometheus.prometheus.svc.cluster.local:9090
        query: scalar (sum (rate (container_cpu_usage_seconds_total{namespace="project"}[10m])) / sum(machine_cpu_cores) * 100)
    