apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-claim
  namespace: project
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi