version: "3.5"

services:
  api:
    build: .
    container_name: pingpong
    image: koxanybak/pingpong
    ports:
      - 8000:8000
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    depends_on:
      - db
  db:
    container_name: pingpong-db
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    command: ["postgres", "-c", "log_statement=all"]
    volumes:
      - /tmp/ppdata:/var/lib/postgresql/data:rw