apiVersion: v1
kind: Pod
metadata:
  name: busybox1
  labels:
    name: busybox1
spec:
  containers:
  - name: busybox
    image: busybox
    imagePullPolicy: IfNotPresent
    command:
    - sleep
    - "3600"
  restartPolicy: Always
