kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: dummysite-controller-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "delete", "create"]
  - apiGroups: ["batch.stable.dwk"]
    resources: ["dummysites"]
    verbs: ["get", "list", "watch", "create", "delete"]