apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-dep
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: koxanybak/todo-api
        readinessProbe:
            initialDelaySeconds: 10
            periodSeconds: 5
            httpGet:
              path: /api/todos/
              port: 8000
        livenessProbe:
            initialDelaySeconds: 20
            periodSeconds: 5
            httpGet:
              path: /api/todos/
              port: 8000
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: todo-cfg
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: todo-cfg
                key: POSTGRES_USER
          - name: NATS
            valueFrom:
              configMapKeyRef:
                name: todo-cfg
                key: NATS
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: POSTGRES_PASSWORD
        resources:
          limits:
            cpu: "150m"
            memory: "100Mi"
