apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-dep
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: koxanybak/todo-api
        env:
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: todo-cfg
                key: POSTGRES_DB
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: todo-cfg
                key: POSTGRES_USER
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: todo-secret
                key: POSTGRES_PASSWORD
