apiVersion: apps/v1
kind: Deployment
metadata:
  name: todo-api-dep
  namespace: project
spec:
  selector:
    matchLabels:
      app: todo-api
  template:
    metadata:
      labels:
        app: todo-api
    spec:
      containers:
      - name: todo-api
        image: koxanybak/todo-api
