name: Release application

on:
  push:

env:
  GKE_CLUSTER: dwk-cluster
  GKE_ZONE: europe-north1-b
  IMAGE: dwk-environments

jobs:
  build-publish-deploy:
    name: Build, Publish and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - uses: google-github-actions/setup-gcloud@master
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
    - run: gcloud container clusters get-credentials "$GKE_CLUSTER" --zone "$GKE_ZONE"

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |-
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    
    - name: Build todo-api
      run: |-
        docker build ./todo-api -t koxanybak/todo-api:latest
    - name: Build todo
      run: |-
        docker build ./todo -t koxanybak/todo:latest

    - name: Docker push
      run: |-
        docker push koxanybak/todo-api
        docker push koxanybak/todo

    - name: Set up Kustomize
      run: |-
        curl -sfLo kustomize https://github.com/kubernetes-sigs/kustomize/releases/download/v3.1.0/kustomize_3.1.0_linux_amd64
        chmod u+x ./kustomize

    - name: Deploy todo-api
      run: |-
        ./kustomize edit set image PROJECT/IMAGE=koxanybak/todo-api
        cd todo-api
        kubectl apply -k .
        kubectl rollout status deployment $IMAGE

    - name: Deploy todo
      run: |-
        ./kustomize edit set image PROJECT/IMAGE=koxanybak/todo
        cd todo
        kubectl apply -k .
        kubectl rollout status deployment $IMAGE